bungee/src/main/java/org/geysermc/floodgate/BungeePlugin.java
If you never complete the intention on async events, bungee waits forever, eventually killing the connection in a timeout. Since conning from java doesn't return a success in the handshake handler, the coder never reaches the other intention completion so you need one in the switch.
=> Fix connection timeouts on java clients

bukkit/src/main/java/org/geysermc/floodgate/PacketHandler.java, bungee/src/main/java/org/geysermc/floodgate/BungeePlugin.java, common/src/main/java/org/geysermc/floodgate/FloodgateConfig.java, common/src/main/java/org/geysermc/floodgate/FloodgatePlayer.java, common/src/main/java/org/geysermc/floodgate/HandshakeHandler.java, velocity/src/main/java/org/geysermc/floodgate/VelocityPlugin.java
A lot of java plugins cannot handle spaces being passed when looking for a username (commands are a huge issue with this). This pr adds an option to replace spaces in names with underscores.
=> Add option to replace spaces in names

bungee/src/main/java/org/geysermc/floodgate/util/CommandUtil.java
Hello! I am using Floodgate with BungeeCord and I have noticed that message is not formatted correctly when I use /linkaccount
And after some investigation I have discovered that the Bungeecord implementation of CommandUtil do not pass args parameter to getOrAddCachedMessage() method.
=> Fix CommandUtil implementation for BungeeCord

bukkit/pom.xml, bukkit/src/main/java/org/geysermc/floodgate/BukkitPlugin.java, bukkit/src/main/java/org/geysermc/floodgate/PacketHandler.java, bukkit/src/main/java/org/geysermc/floodgate/util/ProtocolSupportUtil.java, bukkit/src/main/resources/plugin.yml
This commit hooks into ProtocolSupport to prevent it from attempting an online connection with the Floodgate player. This has been tested with linked accounts and BungeeCord.
=> Add ProtocolSupport support

common/src/main/java/org/geysermc/floodgate/FloodgatePlatform.java
Floodgate's news checking threads should be closed when the `FloodgatePlatform` is being disabled in order to properly shut down the server. Together with GeyserMC/Floodgate-Fabric#40, this should fix GeyserMC/Floodgate-Fabric#25.
=> Properly stop the news checker

core/src/main/java/org/geysermc/floodgate/addon/data/HandshakeDataImpl.java
The replaceAll function use regex to replace text, it calls Pattern.compile() each time the function is called, and since here the character is a blank char, it's useless to use regex. The replace function does the same behavior but without the performance drawback of the regex used.
=> Stop using regex to replace username

.github/workflows/pullrequest.yml
This PR update the pull request workflow since the 2.1.1 branch switched to Gradle.
I updated to actions/checkout@v2 since it's more powerful now according to their GitHub.
Also, I switched to actions/setup-java@v2 because they now have the cached directly in the plugin for maven or Gradle, so less work and finally modifier the directory of upload files.
=> Switch from maven to gradle in workflow

velocity/src/main/java/org/geysermc/floodgate/util/VelocityCommandUtil.java
Actually this function return the optional and then is cast as Player in getUserAudience().
We should return the value of the optional here instead
The error: https://rentry.co/tprhp
=> hotfix(velocity): return the value of optional and not the optional itself

database/mongo/src/main/java/org/geysermc/floodgate/database/MongoDbDatabase.java
Hello, I just tested today's code for personal use and just discovered I introduce a big bug when I make the MongoDB addons.
Actually, the function collectionNotExists wasn't working, and it was causing the plugin not to load when the collections already exist. This fix just adds an empty try-catch, catching the MongoCommandException thrown by Mongo. 
Tested the fix, and it's working.
=> hotfix(database/mongo): fix floodgate not loading with mongo when collection already exists

core/src/main/java/org/geysermc/floodgate/command/LinkAccountCommand.java
We actually cast the player context as UserAudience, but we now provide a ProfileAudience for the argument.
This was causing a CCE.
Error log: https://rentry.co/eaa46
=> fix(core): Switch to ProfileAudience since we require a Profile Audience as player argument

bungee/src/main/java/org/geysermc/floodgate/listener/BungeeListener.java, bungee/src/main/java/org/geysermc/floodgate/pluginmessage/BungeeSkinApplier.java, core/src/main/java/org/geysermc/floodgate/pluginmessage/channel/SkinChannel.java, core/src/main/java/org/geysermc/floodgate/skin/SkinApplier.java, core/src/main/java/org/geysermc/floodgate/skin/SkinUploadSocket.java, spigot/src/main/java/org/geysermc/floodgate/pluginmessage/SpigotSkinApplier.java, velocity/src/main/java/org/geysermc/floodgate/util/VelocitySkinApplier.java
When applying skins to Floodgate players there is a chance of overwriting a skin that another plugin intentionally applied. With this change, all SkinAppliers now check to make sure a player has an empty or null skin before applying a skin to them. This prevents Floodgate from applying a Bedrock skin over a skin that was already set by another plugin.
=> SkinApplier now only applies a skin if a player doesn't already have one

core/src/main/java/org/geysermc/floodgate/util/Utils.java
Languages like ru_RU don't work because they have specific characters, and your files are encoded in UTF-8, but it reads them as ISO 8859-1
=> Use UTF-8 for language files

core/src/main/java/org/geysermc/floodgate/module/CommonModule.java, core/src/main/java/org/geysermc/floodgate/player/FloodgateHandshakeHandler.java
Currently, the disconnect reason if linking is required is always `floodgate.core.not_linked`
The translation key still needs to be added to languages.
Fixes #378 (once languages is also updated)
=> Localize floodgate.core.not_linked

velocity/src/main/java/org/geysermc/floodgate/logger/Slf4jFloodgateLogger.java
This only works because of the circular proxy feature provided by Guice
This fix has already been applied to the JavaUtilFloodgateLogger used by Spigot/BungeeCord
=> Fix injection of LanguageManager/Slf4jFloodgate on Velocity

spigot/src/main/java/org/geysermc/floodgate/util/ClassNames.java
If the server is not a Folia server and you try to run the latest version of Floodgate, you get this stack trace:
```
java.lang.ClassNotFoundException: io.papermc.paper.threadedregions.scheduler.EntityScheduler
[20:24:07 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183)
[20:24:07 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[20:24:07 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
[20:24:07 WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[20:24:07 WARN]: 	at java.base/java.lang.Class.forName(Unknown Source)
[20:24:07 WARN]: 	at floodgate-spigot.jar//org.geysermc.floodgate.util.ReflectionUtils.getClass(ReflectionUtils.java:87)
[20:24:07 WARN]: 	at …
```
=> Check IS_FOLIA silently

bungee/build.gradle.kts
This was done blindly without testing
I suspect that the old commit is no longer available on JitPack, causing builds to fail on GitHub Actions but not Jenkins (due to caching)
=> Bump bungeecord-proxy commit version

spigot/src/main/java/org/geysermc/floodgate/util/SpigotCommandUtil.java, spigot/src/main/java/org/geysermc/floodgate/util/WhitelistUtils.java
I compiled and used this fix myself for a while and it is currently working. It let me add and remove players from the whitelist without any errors. 
I am no expert on Java code, unsure how elegant of a fix this is, but it works for now.
Closes #444
=> Fix spigot whitelist command on newer Paper versions

build-logic/src/main/kotlin/Versions.kt
This should fix AesKeyProducer errors that were fixed in https://github.com/GeyserMC/Geyser/commit/6b67e43f8463aa2ea0672d901e587a22a595ed7a
=> Update Geyser version

bungee/build.gradle.kts, spigot/src/main/java/org/geysermc/floodgate/addon/data/SpigotDataHandler.java, spigot/src/main/java/org/geysermc/floodgate/util/ClassNames.java
Also:
- fixes flipped protocol-version and port in the handshake_packet
- updates languages to https://github.com/GeyserMC/languages/commit/df599a9bc9d7fce93a586591d6c0d625eefe4463 (last pre-dev string version)
- updates bungee dependency (like dev) to be able to build the project
Tested on Spigot 1.20.5 (with Geyser-Standalone), and Paper 1.20.2/1.20.4 (to still be compatible)
Docs/Sources on the fields: 
1.20.5: https://nms.screamingsandals.org/1.20.5/net/minecraft/network/protocol/handshake/ClientIntentionPacket.html
1.20.2: https://nms.screamingsandals.org/1.20.2/net/minecraft/network/protocol/handshake/ClientIntentionPacket.html
=> Support 1.20.5 Spigot

.github/workflows/build.yml, .github/workflows/pullrequest.yml, build-logic/src/main/kotlin/extensions.kt
**Do not merge until the downloads server has been fixed due to the previous PR**
=> Fix Publishing to the Downloads API

core/src/main/java/org/geysermc/floodgate/config/ConfigLoader.java, core/src/main/java/org/geysermc/floodgate/module/CommonModule.java, core/src/main/java/org/geysermc/floodgate/module/ServerCommonModule.java
Will be needed to allow Floodgate-Fabric to provide its own reader that uses the FabricLoader api to retrieve asset files from the mod jar instead of using the classloader method for it (which currently causes issues if any other mod also ships a `config.yml` file at the root of the mod, as Fabric shares the class loader across multiple mods)
=> Allow Floodgate-Fabric to provide its own TemplateReader

build-logic/src/main/kotlin/Versions.kt, spigot/build.gradle.kts, spigot/src/main/java/org/geysermc/floodgate/module/SpigotCommandModule.java
Closes https://github.com/GeyserMC/Floodgate/issues/520
Targets a jitpacked branch of cloud; specifically, this PR: https://github.com/Incendo/cloud-minecraft/pull/78
(that's not fully true; it targets https://github.com/onebeastchris/cloud-minecraft/tree/jitpack as it would otherwise choose java 8 and not build.)
=> 1.21 Spigot support

bungee/src/main/java/org/geysermc/floodgate/inject/bungee/BungeeInjector.java
=> update BungeeCord injector

bungee/src/main/java/org/geysermc/floodgate/inject/bungee/BungeeInjector.java
Some forks like FlameCord have integrated anti-bot features to block connections early. 
By default, Floodgate runs anyways, which not only makes bot attacks affect the server when Floodgate is instaled, but also generate an exception. 
This fixes the issue.
=> Check if channel is open before injecting

bungee/src/main/java/org/geysermc/floodgate/inject/bungee/BungeeInjector.java
The previous commit check if channel is opened but in that point the channel is always opened.
The ReflectionUtils.invoke() can become closed.
Solution finded with debugging and testing. I print when channel become closed and now work correctly
=> Fix of #547
